import './globals.css'
import type { Metadata } from 'next'
import { Angkor, Chonburi, Rubik_Mono_One } from 'next/font/google'
import NavBar from "../components/NavBar";

const angkor = Rubik_Mono_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={`${angkor.className} flex-col flex min-h-screen`}>
        <div className='flex w-full justify-end md:justify-normal'>
          <NavBar/>
        </div>
      {children}
      </body>
    </html>
  )
}
